#!/bin/bash
NET_CONFIG=/etc/sysconfig/network-scripts/ifcfg-eth0
HOSTNAME=/etc/sysconfig/network
NET_RULES="/etc/udev/rules.d/70-persistent-net.rules"
IP=$1
GW=$2

if [ $# != 3 ]; then 
	echo "You must supply arguments - IP Address, Gateway, and Hostname. Exiting..." && exit 1
elif [ "$(id -u)" -ne 0 ]; then 
	echo "You must be root to run the script. Exiting..." && exit 1
fi

#Replacing IP address
/bin/sed -i -r "s/IPADDR=[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}/IPADDR=$IP/g" $NET_CONFIG
/bin/sed -i -r "s/GATEWAY=[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}/GATEWAY=$GW/g" $NET_CONFIG
echo "Configured your IP address and default gateway to be $IP and $GW"
sleep 3

#Replacing hostname
/bin/sed -i '/HOSTNAME/d' $HOSTNAME
echo "HOSTNAME=${3}" >> $HOSTNAME
echo "Configured your hostname to be $3"
sleep 3

#Fixing interface MAC address
/bin/sed -i '/eth0"$/d' $NET_RULES && /bin/sed -i 's/eth1/eth0/g' $NET_RULES
echo "Fixed your mac address. Rebooting..."
sleep 3
/sbin/reboot
